spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:mysql://localhost:3306/restaurent?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update